name: your_project_name
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: ^0.8.4+5
  flutter_barcode_scanner: ^2.0.0
  provider: ^6.0.2
  firebase_core: 
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.5
  firebase_storage: ^10.2.5
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.6
  lottie: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.0.1+1

flutter_native_splash:

  color: "#ffffff"
  image: assets/package.png
  android: true
  ios: true

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true


  # assets:
  #   # Add assets from the images directory to the application.
  #   - assets/images/

  assets:
    # Add assets from the images directory to the application.
    - assets/

